### PR TITLE
Prototype mermaid

### PR DESCRIPTION
**Pull request by neilkidd**
I've been thinking about this and how we could resuse exisiting tools.
Created a manual prototype in mermaid - I think the default layout beats the dot viz one?
See an example ( of mermaid-devops-map.md) in the [![Live Mermaid Editor](https://mermaid.ink/img/eyJjb2RlIjoiZmxvd2NoYXJ0IFRCXG4gICAgQWdpbGVXb3JrKEFnaWxlIFdvcmspXG4gICAgQXV0b21hdGVkVGVzdGluZyhBdXRvbWF0ZWQgVGVzdGluZylcbiAgICBCbHVlL0dyZWVuRGVwbG95bWVudChCbHVlL0dyZWVuIERlcGxveW1lbnQpXG4gICAgQnJhbmNoaW5nU3RyYXRlZ3koQnJhbmNoaW5nIFN0cmF0ZWd5KVxuICAgIENhbmFyeVJlbGVhc2VzKENhbmFyeSBSZWxlYXNlcylcbiAgICBDaGFvc0FnZW50KENoYW9zIEFnZW50KVxuICAgIENvZGVRdWFsaXR5U2NhbnMoQ29kZSBRdWFsaXR5IFNjYW5zKVxuICAgIENvZGVRdWFsaXR5U2NhbnMoQ29kZSBRdWFsaXR5IFNjYW5zKVxuICAgIENvbmZpZ0RhdGFiYXNlL0dpdChDb25maWcgRGF0YWJhc2UvR2l0KVxuICAgIENvbnRhaW5lcmlzZWRBcHBsaWNhdGlvbihDb250YWluZXJpc2VkIEFwcGxpY2F0aW9uKVxuICAgIENvbnRpbnVvdXNEZWxpdmVyeShDb250aW51b3VzIERlbGl2ZXJ5KVxuICAgIENvbnRpbnVvdXNEZXBsb3ltZW50KENvbnRpbnVvdXMgRGVwbG95bWVudClcbiAgICBDb250aW51b3VzSW50ZWdyYXRpb24oQ29udGludW91cyBJbnRlZ3JhdGlvbilcbiAgICBDcm9wc25vdEdhcmRlbnBsYW50cyhDcm9wcyBub3QgR2FyZGVuIHBsYW50cylcbiAgICBEYXJrTGF1bmNoaW5nKERhcmsgTGF1bmNoaW5nKVxuICAgIEV4cGxvcmF0b3J5VGVzdGluZyhFeHBsb3JhdG9yeSBUZXN0aW5nKVxuICAgIEZlYXR1cmVUb2dnbGVzKEZlYXR1cmUgVG9nZ2xlcylcbiAgICBJbW11dGFibGVBcnRlZmFjdHMoSW1tdXRhYmxlIEFydGVmYWN0cylcbiAgICBJbmZyYXN0cnVjdHVyZWFzQ29kZShJbmZyYXN0cnVjdHVyZSBhcyBDb2RlKVxuICAgIE1pY3Jvc2VydmljZUVjb3N5c3RlbShNaWNyb3NlcnZpY2UgRWNvc3lzdGVtKVxuICAgIFBhcmFtZXRyaXNlZEluZnJhc3RydWN0dXJlYXNDb2RlKFBhcmFtZXRyaXNlZCBJbmZyYXN0cnVjdHVyZSBhcyBDb2RlKVxuICAgIFJlbGVhc2VWaWV3cyhSZWxlYXNlIFZpZXdzKVxuICAgIFJlcG9zaXRvcnlDb21wb3NpdGlvbihSZXBvc2l0b3J5IENvbXBvc2l0aW9uKVxuICAgIFNlY3JldHNWYXVsdChTZWNyZXRzIFZhdWx0KVxuICAgIFNlbWFudGljVmVyc2lvbmluZyhTZW1hbnRpYyBWZXJzaW9uaW5nKVxuICAgIFNlcGFyYXRpb25vZmludGVybmFsdmVyc2lvbmluZ2Zyb21NYXJrZXRpbmd2ZXJzaW9uaW5nKFNlcGFyYXRpb24gb2YgaW50ZXJuYWwgdmVyc2lvbmluZyBmcm9tIE1hcmtldGluZyB2ZXJzaW9uaW5nKVxuICAgIFRlc3REcml2ZW5EZXZlbG9wbWVudChUZXN0IERyaXZlbiBEZXZlbG9wbWVudClcbiAgICBVbml0VGVzdGluZyhVbml0IFRlc3RpbmcpXG5cbiAgICBBdXRvbWF0ZWRUZXN0aW5nICA8LS4gQmV0dGVyIFRvZ2V0aGVyIFdpdGggIC4tPiBFeHBsb3JhdG9yeVRlc3RpbmdcbiAgICBBdXRvbWF0ZWRUZXN0aW5nICA8LS4gQmV0dGVyIFRvZ2V0aGVyIFdpdGggIC4tPiBDb2RlUXVhbGl0eVNjYW5zXG4gICAgQXV0b21hdGVkVGVzdGluZyAuLT4gfCBSZWR1Y2VzIEZhaWx1cmUgT2YgfCBDb250aW51b3VzSW50ZWdyYXRpb25cbiAgICBVbml0VGVzdGluZyAtLT4gfCBFbmFibGVzIHwgQ29udGludW91c0ludGVncmF0aW9uXG4gICAgQ29kZVF1YWxpdHlTY2FucyAgPC0uIEJldHRlciBUb2dldGhlciBXaXRoICAuLT4gQWdpbGVXb3JrXG4gICAgQWdpbGVXb3JrIC4tPiB8IFJlZHVjZXMgRmFpbHVyZSBPZiB8IFRlc3REcml2ZW5EZXZlbG9wbWVudFxuICAgIEFnaWxlV29yayAtLT4gfCBFbmFibGVzIHwgQnJhbmNoaW5nU3RyYXRlZ3lcbiAgICBCcmFuY2hpbmdTdHJhdGVneSAtLT4gfCBFbmFibGVzIHwgUmVwb3NpdG9yeUNvbXBvc2l0aW9uXG4gICAgQnJhbmNoaW5nU3RyYXRlZ3kgLS0-IHwgRW5hYmxlcyB8IFBhcmFtZXRyaXNlZEluZnJhc3RydWN0dXJlYXNDb2RlXG4gICAgQnJhbmNoaW5nU3RyYXRlZ3kgLi0-IHwgUmVkdWNlcyBGYWlsdXJlIE9mIHwgQ29udGludW91c0ludGVncmF0aW9uXG4gICAgQnJhbmNoaW5nU3RyYXRlZ3kgLi0-IHwgUmVkdWNlcyBGYWlsdXJlIE9mIHwgSW5mcmFzdHJ1Y3R1cmVhc0NvZGVcbiAgICBJbmZyYXN0cnVjdHVyZWFzQ29kZSAtLT4gfCBFbmFibGVzIHwgQ29udGludW91c0RlbGl2ZXJ5XG4gICAgSW5mcmFzdHJ1Y3R1cmVhc0NvZGUgLS0-IHwgRW5hYmxlcyB8IFBhcmFtZXRyaXNlZEluZnJhc3RydWN0dXJlYXNDb2RlXG4gICAgSW5mcmFzdHJ1Y3R1cmVhc0NvZGUgLi0-IHwgUmVkdWNlcyBGYWlsdXJlIE9mIHwgQ29udGludW91c0RlbGl2ZXJ5XG4gICAgSW5mcmFzdHJ1Y3R1cmVhc0NvZGUgLi0-IHwgUmVkdWNlcyBGYWlsdXJlIE9mIHwgUGFyYW1ldHJpc2VkSW5mcmFzdHJ1Y3R1cmVhc0NvZGVcbiAgICBEYXJrTGF1bmNoaW5nIC4tPiB8IFJlZHVjZXMgRmFpbHVyZSBPZiB8IENvbnRpbnVvdXNEZXBsb3ltZW50XG4gICAgVGVzdERyaXZlbkRldmVsb3BtZW50IC4tPiB8IFJlZHVjZXMgRmFpbHVyZSBPZiB8IFVuaXRUZXN0aW5nXG4gICAgVGVzdERyaXZlbkRldmVsb3BtZW50IC4tPiB8IFJlZHVjZXMgRmFpbHVyZSBPZiB8IEF1dG9tYXRlZFRlc3RpbmdcbiAgICBDb250aW51b3VzSW50ZWdyYXRpb24gLS0-IHwgRW5hYmxlcyB8IENvbnRpbnVvdXNEZWxpdmVyeVxuICAgIENvbnRpbnVvdXNJbnRlZ3JhdGlvbiAtLT4gfCBFbmFibGVzIHwgSW1tdXRhYmxlQXJ0ZWZhY3RzXG4gICAgU2VtYW50aWNWZXJzaW9uaW5nIC0tPiB8IEVuYWJsZXMgfCBSZWxlYXNlVmlld3NcbiAgICBTZW1hbnRpY1ZlcnNpb25pbmcgLi0-IHwgUmVkdWNlcyBGYWlsdXJlIE9mIHwgSW1tdXRhYmxlQXJ0ZWZhY3RzXG4gICAgUmVsZWFzZVZpZXdzIC4tPiB8IFJlZHVjZXMgRmFpbHVyZSBPZiB8IFNlbWFudGljVmVyc2lvbmluZ1xuICAgIFJlbGVhc2VWaWV3cyAtLT4gfCBFbmFibGVzIHwgU2VwYXJhdGlvbm9maW50ZXJuYWx2ZXJzaW9uaW5nZnJvbU1hcmtldGluZ3ZlcnNpb25pbmdcbiAgICBJbW11dGFibGVBcnRlZmFjdHMgLi0-IHwgUmVkdWNlcyBGYWlsdXJlIE9mIHwgQ29udGludW91c0ludGVncmF0aW9uXG4gICAgSW1tdXRhYmxlQXJ0ZWZhY3RzIC0tPiB8IEVuYWJsZXMgfCBTZW1hbnRpY1ZlcnNpb25pbmdcbiAgICBDb250YWluZXJpc2VkQXBwbGljYXRpb24gLi0-IHwgUmVkdWNlcyBGYWlsdXJlIE9mIHwgQ29udGludW91c0RlcGxveW1lbnRcbiAgICBDb250aW51b3VzRGVsaXZlcnkgLS0-IHwgRW5hYmxlcyB8IENvbnRpbnVvdXNEZXBsb3ltZW50XG4gICAgQ29udGludW91c0RlbGl2ZXJ5IC0tPiB8IEVuYWJsZXMgfCBDb250YWluZXJpc2VkQXBwbGljYXRpb25cbiAgICBTZWNyZXRzVmF1bHQgIDwtLiBCZXR0ZXIgVG9nZXRoZXIgV2l0aCAgLi0-IENvbnRpbnVvdXNEZWxpdmVyeVxuICAgIFNlY3JldHNWYXVsdCAgPC0uIEJldHRlciBUb2dldGhlciBXaXRoICAuLT4gQ29udGludW91c0RlcGxveW1lbnRcbiAgICBDb250aW51b3VzRGVwbG95bWVudCAtLT4gfCBFbmFibGVzIHwgRGFya0xhdW5jaGluZ1xuICAgIENvbnRpbnVvdXNEZXBsb3ltZW50IC0tPiB8IEVuYWJsZXMgfCBDcm9wc25vdEdhcmRlbnBsYW50c1xuICAgIENvbnRpbnVvdXNEZXBsb3ltZW50IC0tPiB8IEVuYWJsZXMgfCBDYW5hcnlSZWxlYXNlc1xuICAgIENvbnRpbnVvdXNEZXBsb3ltZW50IC0tPiB8IEVuYWJsZXMgfCBCbHVlL0dyZWVuRGVwbG95bWVudFxuICAgIENvbnRpbnVvdXNEZXBsb3ltZW50IC0tPiB8IEVuYWJsZXMgfCBNaWNyb3NlcnZpY2VFY29zeXN0ZW1cbiAgICBGZWF0dXJlVG9nZ2xlcyAuLT4gfCBSZWR1Y2VzIEZhaWx1cmUgT2YgfCBNaWNyb3NlcnZpY2VFY29zeXN0ZW1cbiAgICBGZWF0dXJlVG9nZ2xlcyAgPC0uIEJldHRlciBUb2dldGhlciBXaXRoICAuLT4gQ29uZmlnRGF0YWJhc2UvR2l0XG4gICAgQ2hhb3NBZ2VudCAuLT4gfCBSZWR1Y2VzIEZhaWx1cmUgT2YgfCBDb250aW51b3VzRGVwbG95bWVudFxuICAgIENyb3Bzbm90R2FyZGVucGxhbnRzIC4tPiB8IFJlZHVjZXMgRmFpbHVyZSBPZiB8IENvbnRpbnVvdXNEZXBsb3ltZW50XG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZmxvd2NoYXJ0IFRCXG4gICAgQWdpbGVXb3JrKEFnaWxlIFdvcmspXG4gICAgQXV0b21hdGVkVGVzdGluZyhBdXRvbWF0ZWQgVGVzdGluZylcbiAgICBCbHVlL0dyZWVuRGVwbG95bWVudChCbHVlL0dyZWVuIERlcGxveW1lbnQpXG4gICAgQnJhbmNoaW5nU3RyYXRlZ3koQnJhbmNoaW5nIFN0cmF0ZWd5KVxuICAgIENhbmFyeVJlbGVhc2VzKENhbmFyeSBSZWxlYXNlcylcbiAgICBDaGFvc0FnZW50KENoYW9zIEFnZW50KVxuICAgIENvZGVRdWFsaXR5U2NhbnMoQ29kZSBRdWFsaXR5IFNjYW5zKVxuICAgIENvZGVRdWFsaXR5U2NhbnMoQ29kZSBRdWFsaXR5IFNjYW5zKVxuICAgIENvbmZpZ0RhdGFiYXNlL0dpdChDb25maWcgRGF0YWJhc2UvR2l0KVxuICAgIENvbnRhaW5lcmlzZWRBcHBsaWNhdGlvbihDb250YWluZXJpc2VkIEFwcGxpY2F0aW9uKVxuICAgIENvbnRpbnVvdXNEZWxpdmVyeShDb250aW51b3VzIERlbGl2ZXJ5KVxuICAgIENvbnRpbnVvdXNEZXBsb3ltZW50KENvbnRpbnVvdXMgRGVwbG95bWVudClcbiAgICBDb250aW51b3VzSW50ZWdyYXRpb24oQ29udGludW91cyBJbnRlZ3JhdGlvbilcbiAgICBDcm9wc25vdEdhcmRlbnBsYW50cyhDcm9wcyBub3QgR2FyZGVuIHBsYW50cylcbiAgICBEYXJrTGF1bmNoaW5nKERhcmsgTGF1bmNoaW5nKVxuICAgIEV4cGxvcmF0b3J5VGVzdGluZyhFeHBsb3JhdG9yeSBUZXN0aW5nKVxuICAgIEZlYXR1cmVUb2dnbGVzKEZlYXR1cmUgVG9nZ2xlcylcbiAgICBJbW11dGFibGVBcnRlZmFjdHMoSW1tdXRhYmxlIEFydGVmYWN0cylcbiAgICBJbmZyYXN0cnVjdHVyZWFzQ29kZShJbmZyYXN0cnVjdHVyZSBhcyBDb2RlKVxuICAgIE1pY3Jvc2VydmljZUVjb3N5c3RlbShNaWNyb3NlcnZpY2UgRWNvc3lzdGVtKVxuICAgIFBhcmFtZXRyaXNlZEluZnJhc3RydWN0dXJlYXNDb2RlKFBhcmFtZXRyaXNlZCBJbmZyYXN0cnVjdHVyZSBhcyBDb2RlKVxuICAgIFJlbGVhc2VWaWV3cyhSZWxlYXNlIFZpZXdzKVxuICAgIFJlcG9zaXRvcnlDb21wb3NpdGlvbihSZXBvc2l0b3J5IENvbXBvc2l0aW9uKVxuICAgIFNlY3JldHNWYXVsdChTZWNyZXRzIFZhdWx0KVxuICAgIFNlbWFudGljVmVyc2lvbmluZyhTZW1hbnRpYyBWZXJzaW9uaW5nKVxuICAgIFNlcGFyYXRpb25vZmludGVybmFsdmVyc2lvbmluZ2Zyb21NYXJrZXRpbmd2ZXJzaW9uaW5nKFNlcGFyYXRpb24gb2YgaW50ZXJuYWwgdmVyc2lvbmluZyBmcm9tIE1hcmtldGluZyB2ZXJzaW9uaW5nKVxuICAgIFRlc3REcml2ZW5EZXZlbG9wbWVudChUZXN0IERyaXZlbiBEZXZlbG9wbWVudClcbiAgICBVbml0VGVzdGluZyhVbml0IFRlc3RpbmcpXG5cbiAgICBBdXRvbWF0ZWRUZXN0aW5nICA8LS4gQmV0dGVyIFRvZ2V0aGVyIFdpdGggIC4tPiBFeHBsb3JhdG9yeVRlc3RpbmdcbiAgICBBdXRvbWF0ZWRUZXN0aW5nICA8LS4gQmV0dGVyIFRvZ2V0aGVyIFdpdGggIC4tPiBDb2RlUXVhbGl0eVNjYW5zXG4gICAgQXV0b21hdGVkVGVzdGluZyAuLT4gfCBSZWR1Y2VzIEZhaWx1cmUgT2YgfCBDb250aW51b3VzSW50ZWdyYXRpb25cbiAgICBVbml0VGVzdGluZyAtLT4gfCBFbmFibGVzIHwgQ29udGludW91c0ludGVncmF0aW9uXG4gICAgQ29kZVF1YWxpdHlTY2FucyAgPC0uIEJldHRlciBUb2dldGhlciBXaXRoICAuLT4gQWdpbGVXb3JrXG4gICAgQWdpbGVXb3JrIC4tPiB8IFJlZHVjZXMgRmFpbHVyZSBPZiB8IFRlc3REcml2ZW5EZXZlbG9wbWVudFxuICAgIEFnaWxlV29yayAtLT4gfCBFbmFibGVzIHwgQnJhbmNoaW5nU3RyYXRlZ3lcbiAgICBCcmFuY2hpbmdTdHJhdGVneSAtLT4gfCBFbmFibGVzIHwgUmVwb3NpdG9yeUNvbXBvc2l0aW9uXG4gICAgQnJhbmNoaW5nU3RyYXRlZ3kgLS0-IHwgRW5hYmxlcyB8IFBhcmFtZXRyaXNlZEluZnJhc3RydWN0dXJlYXNDb2RlXG4gICAgQnJhbmNoaW5nU3RyYXRlZ3kgLi0-IHwgUmVkdWNlcyBGYWlsdXJlIE9mIHwgQ29udGludW91c0ludGVncmF0aW9uXG4gICAgQnJhbmNoaW5nU3RyYXRlZ3kgLi0-IHwgUmVkdWNlcyBGYWlsdXJlIE9mIHwgSW5mcmFzdHJ1Y3R1cmVhc0NvZGVcbiAgICBJbmZyYXN0cnVjdHVyZWFzQ29kZSAtLT4gfCBFbmFibGVzIHwgQ29udGludW91c0RlbGl2ZXJ5XG4gICAgSW5mcmFzdHJ1Y3R1cmVhc0NvZGUgLS0-IHwgRW5hYmxlcyB8IFBhcmFtZXRyaXNlZEluZnJhc3RydWN0dXJlYXNDb2RlXG4gICAgSW5mcmFzdHJ1Y3R1cmVhc0NvZGUgLi0-IHwgUmVkdWNlcyBGYWlsdXJlIE9mIHwgQ29udGludW91c0RlbGl2ZXJ5XG4gICAgSW5mcmFzdHJ1Y3R1cmVhc0NvZGUgLi0-IHwgUmVkdWNlcyBGYWlsdXJlIE9mIHwgUGFyYW1ldHJpc2VkSW5mcmFzdHJ1Y3R1cmVhc0NvZGVcbiAgICBEYXJrTGF1bmNoaW5nIC4tPiB8IFJlZHVjZXMgRmFpbHVyZSBPZiB8IENvbnRpbnVvdXNEZXBsb3ltZW50XG4gICAgVGVzdERyaXZlbkRldmVsb3BtZW50IC4tPiB8IFJlZHVjZXMgRmFpbHVyZSBPZiB8IFVuaXRUZXN0aW5nXG4gICAgVGVzdERyaXZlbkRldmVsb3BtZW50IC4tPiB8IFJlZHVjZXMgRmFpbHVyZSBPZiB8IEF1dG9tYXRlZFRlc3RpbmdcbiAgICBDb250aW51b3VzSW50ZWdyYXRpb24gLS0-IHwgRW5hYmxlcyB8IENvbnRpbnVvdXNEZWxpdmVyeVxuICAgIENvbnRpbnVvdXNJbnRlZ3JhdGlvbiAtLT4gfCBFbmFibGVzIHwgSW1tdXRhYmxlQXJ0ZWZhY3RzXG4gICAgU2VtYW50aWNWZXJzaW9uaW5nIC0tPiB8IEVuYWJsZXMgfCBSZWxlYXNlVmlld3NcbiAgICBTZW1hbnRpY1ZlcnNpb25pbmcgLi0-IHwgUmVkdWNlcyBGYWlsdXJlIE9mIHwgSW1tdXRhYmxlQXJ0ZWZhY3RzXG4gICAgUmVsZWFzZVZpZXdzIC4tPiB8IFJlZHVjZXMgRmFpbHVyZSBPZiB8IFNlbWFudGljVmVyc2lvbmluZ1xuICAgIFJlbGVhc2VWaWV3cyAtLT4gfCBFbmFibGVzIHwgU2VwYXJhdGlvbm9maW50ZXJuYWx2ZXJzaW9uaW5nZnJvbU1hcmtldGluZ3ZlcnNpb25pbmdcbiAgICBJbW11dGFibGVBcnRlZmFjdHMgLi0-IHwgUmVkdWNlcyBGYWlsdXJlIE9mIHwgQ29udGludW91c0ludGVncmF0aW9uXG4gICAgSW1tdXRhYmxlQXJ0ZWZhY3RzIC0tPiB8IEVuYWJsZXMgfCBTZW1hbnRpY1ZlcnNpb25pbmdcbiAgICBDb250YWluZXJpc2VkQXBwbGljYXRpb24gLi0-IHwgUmVkdWNlcyBGYWlsdXJlIE9mIHwgQ29udGludW91c0RlcGxveW1lbnRcbiAgICBDb250aW51b3VzRGVsaXZlcnkgLS0-IHwgRW5hYmxlcyB8IENvbnRpbnVvdXNEZXBsb3ltZW50XG4gICAgQ29udGludW91c0RlbGl2ZXJ5IC0tPiB8IEVuYWJsZXMgfCBDb250YWluZXJpc2VkQXBwbGljYXRpb25cbiAgICBTZWNyZXRzVmF1bHQgIDwtLiBCZXR0ZXIgVG9nZXRoZXIgV2l0aCAgLi0-IENvbnRpbnVvdXNEZWxpdmVyeVxuICAgIFNlY3JldHNWYXVsdCAgPC0uIEJldHRlciBUb2dldGhlciBXaXRoICAuLT4gQ29udGludW91c0RlcGxveW1lbnRcbiAgICBDb250aW51b3VzRGVwbG95bWVudCAtLT4gfCBFbmFibGVzIHwgRGFya0xhdW5jaGluZ1xuICAgIENvbnRpbnVvdXNEZXBsb3ltZW50IC0tPiB8IEVuYWJsZXMgfCBDcm9wc25vdEdhcmRlbnBsYW50c1xuICAgIENvbnRpbnVvdXNEZXBsb3ltZW50IC0tPiB8IEVuYWJsZXMgfCBDYW5hcnlSZWxlYXNlc1xuICAgIENvbnRpbnVvdXNEZXBsb3ltZW50IC0tPiB8IEVuYWJsZXMgfCBCbHVlL0dyZWVuRGVwbG95bWVudFxuICAgIENvbnRpbnVvdXNEZXBsb3ltZW50IC0tPiB8IEVuYWJsZXMgfCBNaWNyb3NlcnZpY2VFY29zeXN0ZW1cbiAgICBGZWF0dXJlVG9nZ2xlcyAuLT4gfCBSZWR1Y2VzIEZhaWx1cmUgT2YgfCBNaWNyb3NlcnZpY2VFY29zeXN0ZW1cbiAgICBGZWF0dXJlVG9nZ2xlcyAgPC0uIEJldHRlciBUb2dldGhlciBXaXRoICAuLT4gQ29uZmlnRGF0YWJhc2UvR2l0XG4gICAgQ2hhb3NBZ2VudCAuLT4gfCBSZWR1Y2VzIEZhaWx1cmUgT2YgfCBDb250aW51b3VzRGVwbG95bWVudFxuICAgIENyb3Bzbm90R2FyZGVucGxhbnRzIC4tPiB8IFJlZHVjZXMgRmFpbHVyZSBPZiB8IENvbnRpbnVvdXNEZXBsb3ltZW50XG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

## Ideas

- Rework the python to generate the markdown as per [mermaid-devops-map.md](https://raw.githubusercontent.com/Sam-Rowe/DevOps-Map/f68e35fa3cb6027ac0d80532bafcb0cf5fe343fb/mermaid-devops-map.md)
-  Investigate calling the mermaid API to generate images / svg
-  Use the [mermaid github action](https://github.com/neenjaw/compile-mermaid-markdown-action)

If you think it's worth pursuing - let's talk 😄.

### CODE REVIEW

**Comment by Sam-Rowe** [comment]
Hi @neilkidd Thank you! 

Totally agree the Mermaid diagram does give us a much better output than the SVG. 

Does the JSON file with its ability to capture extra info still add value? If it does I might play with a python script to generate the mermaid from the JSON?

**Review by Sam-Rowe — APPROVED** [review]
Thank you for fixing my typo's!

**Comment by neilkidd** [comment]
> 
> 
> Hi @neilkidd Thank you!
> 
> Totally agree the Mermaid diagram does give us a much better output than the SVG.
> 
> Does the JSON file with its ability to capture extra info still add value? If it does I might play with a python script to generate the mermaid from the JSON?

As it stands the mermaid file **is lossy** - I suggest we assess what it lost and the value.
It did occur to me that the json could be replaced - needs a chat.

**Comment by Sam-Rowe** [comment]
Let's organise some time for a chat on this. I really appreciate your input @neilkidd

**Pull request merged**
